// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.3
// Project name: battery

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Button1;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Speed_Number_2;
lv_obj_t *ui_Speed_Number_1;
lv_obj_t *ui_speedd;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Battery;
lv_obj_t *ui_Batterypanel;
lv_obj_t *ui_Bar2;
lv_obj_t *ui_Image5;
lv_obj_t *ui_Batterypanel1;
lv_obj_t *ui_Bar3;
lv_obj_t *ui_Image2;
lv_obj_t *ui_Label3;
lv_obj_t *ui_speedd1;
lv_obj_t *ui_speedd2;
lv_obj_t *ui_Label4;
lv_obj_t *ui_speedd3;
lv_obj_t *ui_speedd4;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Label10;
lv_obj_t *ui_Label12;
lv_obj_t *ui_Title;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Label17;
lv_obj_t *ui_batterypercentagevolumne;
lv_obj_t *ui_Label13;
lv_obj_t *ui_batterypercentagevolumne1;
lv_obj_t *ui_Label16;
lv_obj_t *ui_regeneratedpanel;
lv_obj_t *ui_Label19;
lv_obj_t *ui_Label20;
lv_obj_t *ui_Label21;
lv_obj_t *ui_Label22;
lv_obj_t *ui_Label23;
lv_obj_t *ui_Label14;
lv_obj_t *ui_Slider1;
lv_obj_t *ui_flash;
lv_obj_t *ui_Slider2;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_Label18;
lv_obj_t *ui_Label1;
lv_obj_t *ui_footer;
lv_obj_t *ui_Bar1;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label6;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
