// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.3
// Project name: battery

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Screen1, &ui_img_ebike_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Button1 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_Button1, 50);
lv_obj_set_height( ui_Button1, 46);
lv_obj_set_x( ui_Button1, 357 );
lv_obj_set_y( ui_Button1, -203 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button1, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x0FB3E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Button1, lv_color_hex(0xCC1515), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Button1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Button1, &ui_img_icn_charge_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_color(ui_Button1, lv_color_hex(0x14D3EA), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_Button1, 1, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_Button1, 10, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_Button1, lv_color_hex(0x0EE9F0), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_Button1, 50, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_Button1, 5, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label5 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 288 );
lv_obj_set_y( ui_Label5, -200 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Eco");
lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label5, &ui_font_Big, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Speed_Number_2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Speed_Number_2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Speed_Number_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Speed_Number_2, -60 );
lv_obj_set_y( ui_Speed_Number_2, 0 );
lv_obj_set_align( ui_Speed_Number_2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Speed_Number_2,"32");
lv_obj_set_style_text_color(ui_Speed_Number_2, lv_color_hex(0xD56920), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Speed_Number_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Speed_Number_2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Speed_Number_2, &ui_font_Number, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Speed_Number_1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Speed_Number_1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Speed_Number_1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Speed_Number_1, -67 );
lv_obj_set_y( ui_Speed_Number_1, 0 );
lv_obj_set_align( ui_Speed_Number_1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Speed_Number_1,"32");
lv_obj_set_style_text_color(ui_Speed_Number_1, lv_color_hex(0xFFE69C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Speed_Number_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Speed_Number_1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Speed_Number_1, &ui_font_Number, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_speedd = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_speedd, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_speedd, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_speedd, -98 );
lv_obj_set_y( ui_speedd, -72 );
lv_obj_set_align( ui_speedd, LV_ALIGN_CENTER );
lv_label_set_text(ui_speedd,"Speed");
lv_obj_set_style_text_color(ui_speedd, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_speedd, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_speedd, &ui_font_Iltatic_style, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -28 );
lv_obj_set_y( ui_Label8, 59 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Km/h");
lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x848A8D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label8, &ui_font_Iltatic_style, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Battery = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Battery, 394);
lv_obj_set_height( ui_Battery, 349);
lv_obj_set_x( ui_Battery, 209 );
lv_obj_set_y( ui_Battery, -14 );
lv_obj_set_align( ui_Battery, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Battery, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Battery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Battery, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Battery, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Battery, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Batterypanel = lv_obj_create(ui_Battery);
lv_obj_set_width( ui_Batterypanel, 100);
lv_obj_set_height( ui_Batterypanel, 177);
lv_obj_set_x( ui_Batterypanel, -152 );
lv_obj_set_y( ui_Batterypanel, -4 );
lv_obj_set_align( ui_Batterypanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Batterypanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Batterypanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Batterypanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Batterypanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Batterypanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar2 = lv_bar_create(ui_Batterypanel);
lv_bar_set_value(ui_Bar2,30,LV_ANIM_OFF);
lv_obj_set_width( ui_Bar2, 50);
lv_obj_set_height( ui_Bar2, 113);
lv_obj_set_align( ui_Bar2, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Bar2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Bar2, lv_color_hex(0xE3D6D6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Bar2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Bar2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Bar2, lv_color_hex(0x09F8E7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Bar2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Bar2, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Bar2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Bar2, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0x0D0D0D), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Bar2, lv_color_hex(0x33F022), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Bar2, LV_GRAD_DIR_VER, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Image5 = lv_img_create(ui_Batterypanel);
lv_img_set_src(ui_Image5, &ui_img_icn_charge_png);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image5, 26 );
lv_obj_set_y( ui_Image5, 4 );
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Batterypanel1 = lv_obj_create(ui_Battery);
lv_obj_set_width( ui_Batterypanel1, 100);
lv_obj_set_height( ui_Batterypanel1, 177);
lv_obj_set_x( ui_Batterypanel1, 46 );
lv_obj_set_y( ui_Batterypanel1, -4 );
lv_obj_set_align( ui_Batterypanel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Batterypanel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Batterypanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Batterypanel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Batterypanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Batterypanel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar3 = lv_bar_create(ui_Batterypanel1);
lv_bar_set_value(ui_Bar3,10,LV_ANIM_OFF);
lv_obj_set_width( ui_Bar3, 50);
lv_obj_set_height( ui_Bar3, 113);
lv_obj_set_x( ui_Bar3, 0 );
lv_obj_set_y( ui_Bar3, -1 );
lv_obj_set_align( ui_Bar3, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Bar3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Bar3, lv_color_hex(0xE3D6D6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Bar3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Bar3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Bar3, lv_color_hex(0x09F8E7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Bar3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Bar3, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Bar3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Bar3, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0x0D0D0D), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar3, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Bar3, lv_color_hex(0x33F022), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Bar3, LV_GRAD_DIR_VER, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_Batterypanel1);
lv_img_set_src(ui_Image2, &ui_img_icn_charge_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image2, 26 );
lv_obj_set_y( ui_Image2, 4 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_Battery);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -60 );
lv_obj_set_y( ui_Label3, -20 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"40v");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xEBEBEB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &ui_font_batteryv, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_speedd1 = lv_label_create(ui_Battery);
lv_obj_set_width( ui_speedd1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_speedd1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_speedd1, -56 );
lv_obj_set_y( ui_speedd1, -51 );
lv_obj_set_align( ui_speedd1, LV_ALIGN_CENTER );
lv_label_set_text(ui_speedd1,"Battery");
lv_obj_set_style_text_color(ui_speedd1, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_speedd1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_speedd1, &ui_font_Iltatic_style, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_speedd2 = lv_label_create(ui_Battery);
lv_obj_set_width( ui_speedd2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_speedd2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_speedd2, 138 );
lv_obj_set_y( ui_speedd2, -51 );
lv_obj_set_align( ui_speedd2, LV_ALIGN_CENTER );
lv_label_set_text(ui_speedd2,"Battery");
lv_obj_set_style_text_color(ui_speedd2, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_speedd2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_speedd2, &ui_font_Iltatic_style, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_Battery);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 134 );
lv_obj_set_y( ui_Label4, -21 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"20V");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xEBEBEB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label4, &ui_font_batteryv, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_speedd3 = lv_label_create(ui_Battery);
lv_obj_set_width( ui_speedd3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_speedd3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_speedd3, -54 );
lv_obj_set_y( ui_speedd3, 10 );
lv_obj_set_align( ui_speedd3, LV_ALIGN_CENTER );
lv_label_set_text(ui_speedd3,"Distance");
lv_obj_set_style_text_color(ui_speedd3, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_speedd3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_speedd3, &ui_font_Iltatic_style, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_speedd4 = lv_label_create(ui_Battery);
lv_obj_set_width( ui_speedd4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_speedd4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_speedd4, 134 );
lv_obj_set_y( ui_speedd4, 10 );
lv_obj_set_align( ui_speedd4, LV_ALIGN_CENTER );
lv_label_set_text(ui_speedd4,"Distance");
lv_obj_set_style_text_color(ui_speedd4, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_speedd4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_speedd4, &ui_font_Iltatic_style, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_Battery);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, -68 );
lv_obj_set_y( ui_Label9, 41 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"84.6 ");
lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xEBEBEB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label9, &ui_font_batteryv, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_Battery);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, -21 );
lv_obj_set_y( ui_Label11, 40 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"Km");
lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x848A8D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label11, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_Battery);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, 112 );
lv_obj_set_y( ui_Label10, 41 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"30");
lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xEBEBEB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label10, &ui_font_batteryv, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label12 = lv_label_create(ui_Battery);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label12, 151 );
lv_obj_set_y( ui_Label12, 40 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"Km");
lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x848A8D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label12, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Title = lv_obj_create(ui_Battery);
lv_obj_set_width( ui_Title, 369);
lv_obj_set_height( ui_Title, 50);
lv_obj_set_x( ui_Title, 32 );
lv_obj_set_y( ui_Title, -118 );
lv_obj_set_align( ui_Title, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Title, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Title, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Title, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Title, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Title);
lv_img_set_src(ui_Image1, &ui_img_menu_line_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image1, 27 );
lv_obj_set_y( ui_Image1, -1 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label17 = lv_label_create(ui_Title);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label17, 32 );
lv_obj_set_y( ui_Label17, -4 );
lv_obj_set_align( ui_Label17, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label17,"Battery Information");
lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label17, &ui_font_batteryv, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batterypercentagevolumne = lv_obj_create(ui_Battery);
lv_obj_set_width( ui_batterypercentagevolumne, 100);
lv_obj_set_height( ui_batterypercentagevolumne, 50);
lv_obj_set_x( ui_batterypercentagevolumne, -134 );
lv_obj_set_y( ui_batterypercentagevolumne, 91 );
lv_obj_set_align( ui_batterypercentagevolumne, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_batterypercentagevolumne, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_batterypercentagevolumne, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batterypercentagevolumne, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_batterypercentagevolumne, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_batterypercentagevolumne, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label13 = lv_label_create(ui_batterypercentagevolumne);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label13, -3 );
lv_obj_set_y( ui_Label13, -1 );
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"30 %");
lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFCE470), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label13, &ui_font_batteryv, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batterypercentagevolumne1 = lv_obj_create(ui_Battery);
lv_obj_set_width( ui_batterypercentagevolumne1, 100);
lv_obj_set_height( ui_batterypercentagevolumne1, 48);
lv_obj_set_x( ui_batterypercentagevolumne1, 56 );
lv_obj_set_y( ui_batterypercentagevolumne1, 95 );
lv_obj_set_align( ui_batterypercentagevolumne1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_batterypercentagevolumne1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_batterypercentagevolumne1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batterypercentagevolumne1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_batterypercentagevolumne1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_batterypercentagevolumne1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label16 = lv_label_create(ui_batterypercentagevolumne1);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label16, -3 );
lv_obj_set_y( ui_Label16, -1 );
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"10 %");
lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFCE470), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label16, &ui_font_batteryv, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_regeneratedpanel = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_regeneratedpanel, 143);
lv_obj_set_height( ui_regeneratedpanel, 401);
lv_obj_set_x( ui_regeneratedpanel, -1 );
lv_obj_set_y( ui_regeneratedpanel, 38 );
lv_obj_clear_flag( ui_regeneratedpanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_regeneratedpanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_regeneratedpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_regeneratedpanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_regeneratedpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label19 = lv_label_create(ui_regeneratedpanel);
lv_obj_set_width( ui_Label19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label19, -8 );
lv_obj_set_y( ui_Label19, 103 );
lv_obj_set_align( ui_Label19, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label19,"25#94aeb4 %");
lv_label_set_recolor(ui_Label19,"true");
lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label19, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label20 = lv_label_create(ui_regeneratedpanel);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label20, -15 );
lv_obj_set_y( ui_Label20, -99 );
lv_obj_set_align( ui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label20,"75#94aeb4 %");
lv_label_set_recolor(ui_Label20,"true");
lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label20, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label21 = lv_label_create(ui_regeneratedpanel);
lv_obj_set_width( ui_Label21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label21, -36 );
lv_obj_set_y( ui_Label21, -8 );
lv_obj_set_align( ui_Label21, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label21,"50#94aeb4 %");
lv_label_set_recolor(ui_Label21,"true");
lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label21, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label22 = lv_label_create(ui_regeneratedpanel);
lv_obj_set_width( ui_Label22, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label22, 34 );
lv_obj_set_y( ui_Label22, -192 );
lv_obj_set_align( ui_Label22, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label22,"100#94aeb4 %");
lv_label_set_recolor(ui_Label22,"true");
lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label22, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label23 = lv_label_create(ui_regeneratedpanel);
lv_obj_set_width( ui_Label23, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label23, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label23, 47 );
lv_obj_set_y( ui_Label23, 170 );
lv_obj_set_align( ui_Label23, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label23,"10#94aeb4 %");
lv_label_set_recolor(ui_Label23,"true");
lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label23, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label14 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label14, 25 );
lv_obj_set_y( ui_Label14, -214 );
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label14,"11:45 PM");
lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label14, &ui_font_batteryv, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Slider1 = lv_slider_create(ui_Screen1);
lv_slider_set_value( ui_Slider1, 5, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider1)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider1, 334);
lv_obj_set_height( ui_Slider1, 388);
lv_obj_set_x( ui_Slider1, -244 );
lv_obj_set_y( ui_Slider1, 2 );
lv_obj_set_align( ui_Slider1, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Slider1, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Slider1, &ui_img_slider_battery_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

lv_obj_set_style_radius(ui_Slider1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_flash = lv_img_create(ui_Screen1);
lv_img_set_src(ui_flash, &ui_img_icn_flash_png);
lv_obj_set_width( ui_flash, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_flash, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_flash, -69 );
lv_obj_set_y( ui_flash, 99 );
lv_obj_set_align( ui_flash, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_flash, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_flash, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_flash,500);

ui_Slider2 = lv_slider_create(ui_Screen1);
lv_slider_set_value( ui_Slider2, 5, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider2)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider2, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider2, 213);
lv_obj_set_height( ui_Slider2, 396);
lv_obj_set_x( ui_Slider2, -165 );
lv_obj_set_y( ui_Slider2, -1 );
lv_obj_set_align( ui_Slider2, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Slider2, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Slider2, &ui_img_speed_slider_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel3, 78);
lv_obj_set_height( ui_Panel3, 32);
lv_obj_set_x( ui_Panel3, -23 );
lv_obj_set_y( ui_Panel3, 101 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel3,LV_FLEX_FLOW_ROW_REVERSE);
lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label18 = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label18, 10 );
lv_obj_set_y( ui_Label18, 2 );
lv_obj_set_align( ui_Label18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label18,"V");
lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xADA5A5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label18, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 130 );
lv_obj_set_y( ui_Label1, 261 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"5.5");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &ui_font_percentagekm, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_footer = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_footer, 779);
lv_obj_set_height( ui_footer, 68);
lv_obj_set_x( ui_footer, -4 );
lv_obj_set_y( ui_footer, 202 );
lv_obj_set_align( ui_footer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_footer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_footer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_footer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_footer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_footer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar1 = lv_bar_create(ui_footer);
lv_bar_set_value(ui_Bar1,25,LV_ANIM_OFF);
lv_obj_set_width( ui_Bar1, 644);
lv_obj_set_height( ui_Bar1, 17);
lv_obj_set_x( ui_Bar1, -39 );
lv_obj_set_y( ui_Bar1, -2 );
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Bar1, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x12130D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Bar1, lv_color_hex(0x141614), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Bar1, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Bar1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Bar1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Bar1, lv_color_hex(0xF3A31C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Bar1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Bar1, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Bar1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Bar1, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xF74009), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Bar1, lv_color_hex(0xF97907), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Bar1, LV_GRAD_DIR_VER, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_footer);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 327 );
lv_obj_set_y( ui_Label2, -2 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"+24.7");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &ui_font_percentagekm, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_footer);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 378 );
lv_obj_set_y( ui_Label6, -1 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"°C");
lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xB8C9CD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label6, &ui_font_Small, LV_PART_MAIN| LV_STATE_DEFAULT);

}
